### ISSUE TITLE
[request] add history of browsing

### ISSUE THREAD

**Issue by 3xploiton3** [HandyOrg/HandySub#82]

**Comment by ghost1372** [comment]
Great idea
I will add a AutoSuggestBox soon
![image](https://user-images.githubusercontent.com/9213496/106359358-920afc80-6327-11eb-8aa8-e7cce56b43eb.png)

**Comment by ghost1372** [comment]
@3xploiton3  History Added😁
I limited the history to 20 items, I think that's enough
After 20, the oldest item will be deleted

![0](https://user-images.githubusercontent.com/9213496/106363646-01401b00-633f-11eb-887a-67c1242ebcca.png)
![01](https://user-images.githubusercontent.com/9213496/106363650-0735fc00-633f-11eb-8469-535d2c1b4a90.png)
