### ISSUE TITLE
[request] secondary or filter languages

### ISSUE THREAD

**Issue by 3xploiton3** [HandyOrg/HandySub#83]
![image](https://user-images.githubusercontent.com/19517680/106359836-a4952e00-6347-11eb-88bf-bd9a1cb5c733.png)

or maybe custom language, i always download 2 language english and indonesia, 

subscene already have this filter, very useful
![image](https://user-images.githubusercontent.com/19517680/106359886-ffc72080-6347-11eb-9d45-99eda953f374.png)

**Comment by ghost1372** [comment]
Good😉
I need more time to implement this feature because it may change the main structure of the project

**Comment by ghost1372** [comment]
Hi @3xploiton3 Sorry for the delay
Try version 3 😄
I added this feature
I also designed the program from scratch, now the performance and UI is much better
https://github.com/HandyOrg/HandySub/releases/tag/v3.0.0.0
