### ISSUE TITLE
subscene function broken

### ISSUE THREAD

**Issue by 3xploiton3** [HandyOrg/HandySub#84]
![image](https://user-images.githubusercontent.com/19517680/107124245-3ddabc00-68d5-11eb-9ddf-5965530d9f3c.png)

**Comment by ghost1372** [comment]
No problem it works
Subscene site sometimes slows down and does not send a proper response
For this reason you receive an error message, after receiving the error you can repeat this several times to finally get the result
![Untitled](https://user-images.githubusercontent.com/9213496/107128027-b5a5e800-68cf-11eb-81bb-f298a3e04f9b.png)

**Comment by 3xploiton3** [comment]
> No problem it works
> Subscene site sometimes slows down and does not send a proper response
> For this reason you receive an error message, after receiving the error you can repeat this several times to finally get the result
> ![Untitled](https://user-images.githubusercontent.com/9213496/107128027-b5a5e800-68cf-11eb-81bb-f298a3e04f9b.png)

which version is this?

<details>

![image](https://user-images.githubusercontent.com/19517680/107132553-99776a80-6912-11eb-8e23-6bb9d84bdd1e.png)
</details>

**Comment by ghost1372** [comment]
> > No problem it works
> > Subscene site sometimes slows down and does not send a proper response
> > For this reason you receive an error message, after receiving the error you can repeat this several times to finally get the result
> > ![Untitled](https://user-images.githubusercontent.com/9213496/107128027-b5a5e800-68cf-11eb-81bb-f298a3e04f9b.png)
> 
> which version is this?
> 
> 
> my version
> <details>
> 
> ![image](https://user-images.githubusercontent.com/19517680/107132553-99776a80-6912-11eb-8e23-6bb9d84bdd1e.png)
> </details>
> 
> 

This is a new version, I have not uploaded it yet, I am working on it
