### ISSUE TITLE
دکمه برگشت

### ISSUE THREAD

**Issue by CleVeR-eRore** [HandyOrg/HandySub#85]
سلام
بعد از اینکه اسم زیرنویس را در قسمت جهان زیرنویس سرچ کردیم و آیتم ها اومدند، اگه اشتباهی روی یکی کلیک کنیم هیچ دکمه بازگشتی وجود ندارد و مجبوریم دوباره اقدام به سرچ کنیم. خیلی راحت تر میشود اگر دکمه بازگشتی در قسمت بالای صفحه گذاشته شود

**Comment by ghost1372** [comment]
@CleVeR-eRore 
سلام در قسمت تنظیمات گزینه ای به اسم **ماندگاری صفحات بعد از تغییر صفحه** وجود داره که اگر این گزینه رو فعال کنید به قسمت بالای منوی برنامه یه دکمه با ایکون فلش ظاهر میشه (اگر با فعال کردن دکمه رو مشاهده نکردید یکبار دیگه غیرفعال و دوباره فعالش کنید) 
انشالله طی روزهای اینده دوباره از اول قراره برنامه رو بازنویسی کنم اگر شرایط خوب پیش بره قابلیت برگشت رو بصورت پیشفرض درنظر میگیرم

**Comment by CleVeR-eRore** [comment]
@ghost1372 
بله دقیقا... همینم خوبه
