### ISSUE TITLE
[Feature Request] Language Support

### ISSUE THREAD

**Issue by as280093** [HandyOrg/HandySub#88]
Currently Subtitle are downloaded in zip and in bundle 
it could be best to choose only one languages and without zip just srt file

**Comment by ghost1372** [comment]
Subtitles downloaded from subscene or other sites are automatically downloaded as zip, HandySub is not involved in bundling subtitles. However, HandySub can unzip the file after downloading So I will add this feature soon

**Comment by 3xploiton3** [comment]
can u add option in setting to always choose priority language?

like u did in version 2.1 
![image](https://user-images.githubusercontent.com/19517680/121192000-b444f600-c896-11eb-9d79-51c1324270a1.png)

**Comment by ghost1372** [comment]
this option exist but moved to subtitle download page next to search box
![image](https://user-images.githubusercontent.com/9213496/121197346-7a6bf380-c886-11eb-8d94-13fb1de888ca.png)
