### ISSUE TITLE
open folder error

### ISSUE THREAD

**Issue by 3xploiton3** [HandyOrg/HandySub#90]
https://user-images.githubusercontent.com/19517680/121193284-e9057d00-c897-11eb-934e-4f789e761ab3.mp4

after download subs, open folder cannot open to destination

![image](https://user-images.githubusercontent.com/19517680/121193506-194d1b80-c898-11eb-8a62-ab8ea73c3228.png)

**Comment by ghost1372** [comment]
thank you i will fix this issue

**Comment by ghost1372** [comment]
This is because the auto unzip option is probably enabled in settings, However, this issue has been fixed in the new version (under development) and We also use a new look for this
![sub](https://user-images.githubusercontent.com/9213496/127639874-65f4be81-8cc1-4e04-a9a5-c3d52bd84725.gif)
