### ISSUE TITLE
notification auto close

### ISSUE THREAD

**Issue by 3xploiton3** [HandyOrg/HandySub#91]
please make option setting notif auto close in 5 second or more
![image](https://user-images.githubusercontent.com/19517680/124080628-c7ea1380-da74-11eb-8cff-9452792c41c3.png)

**Comment by ghost1372** [comment]
In the new version (in development) the way of displaying notifications has changed and does not bother the user 
![image](https://user-images.githubusercontent.com/9213496/127638905-2e2f6983-9de8-4ea6-b442-c890864e40a9.png)
