### ISSUE TITLE
unzip sub after download completed doesn't work

### ISSUE THREAD

**Issue by 3xploiton3** [HandyOrg/HandySub#93]
![image](https://user-images.githubusercontent.com/19517680/125380295-2cce3380-e3bc-11eb-82cd-b12fa6e7b389.png)

unzip subs after download completed doesn't work

**Comment by ghost1372** [comment]
I think your file is rar, Currently we only support zip format in next version we will support RAR

**Comment by 3xploiton3** [comment]
file is zip

![image](https://user-images.githubusercontent.com/19517680/125405652-23f05880-e3e2-11eb-9311-0895086bdf75.png)

**Comment by ghost1372** [comment]
So mybe your zip is not downloaded properly. can you open your zip with winrar?

**Comment by 3xploiton3** [comment]
its because i use IDM
